### ISSUE TITLE
About section

### ISSUE THREAD

**Issue by claudioccm** [ClaudioMendoncaDesign/citizen-budget-website#12]
Rather than have the text to the right and the image to the left, let’s have the text running across the whole page, and a couple images in between both paragraphs. Make the text a bit larger as well and we made a few edits to this text, see google content doc.

**Comment by claudioccm** [comment]
@lharv076, do we have the about text updated in the french version too?

**Comment by claudioccm** [comment]
partially fixed, just waiting on the the answer for the french text

**Comment by lharv076** [comment]
yes, it's in the FR doc (https://docs.google.com/document/d/1URq4NUUjun8FCPZjdIUMG0LePPeo-kX77GmB-tMsYIc/edit#heading=h.gjdgxs)

I just translated the last quote as well.

**Comment by lharv076** [comment]
Looks so much better like this! Do you need a third picture? (two of them are the same right now) Can we just have two instead of 3?

The tagline in the about section was previously edited and didn't make it in. It's in red in the [content doc](https://docs.google.com/document/d/1jeCYVUz_a6tiUd7WFjl0taTwOOdUMaNL7C6VXzqeHxI/edit#heading=h.me5ugras2wz5)

**Comment by lharv076** [comment]
@claudioccm 

Hey,

Just need to edit the tagline in the about section so it reads:

_Citizen Budget simulator is used by over 50 cities; reaching 6 million citizens, coast-to-coast to significantly boost their budget consultations_

**Comment by claudioccm** [comment]
ok, no problem. Can you send me the french version?

**Comment by lharv076** [comment]
The about section in the french version is good.

Just need to edit the first point under "Fonctionnalités optionnelles" (optional features) so it reads:

_Contactez-nous pour en savoir plus sur notre gamme de personnalisations novatrices pour accroître la participation des citoyens dans votre processus budgétaire_

And the footer so it reads:

_Budget Citoyen est un produit de Nord Ouvert, un organisme canadien à but non lucratif, une entreprise sociale qui se spécialise dans le développement d’outils en ligne innovateurs qui font la promotion de la transparence gouvernementale et de la participation citoyenne._

And that will be all for text edits, we'll be all up to date with them.

**Comment by claudioccm** [comment]
awesome!!!!!!! I will get it ready for you in no time

**Comment by lharv076** [comment]
ok wicked! 

I also just noticed that in the French version, we still need to move the "Contactez-nous" button so that it's completely at the end, and put the following text where it is now:

_Lancez votre consultation budgétaire en ligne en peu de temps - contactez-nous pour savoir comment!_

(like the anglo version)
